version: '2'
services:
    rbac-app:
        image: rbac
        external_links:
            - rbac-mysql:mysql
            - rbac-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rbac?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    rbac-mysql:
        extends:
            file: mysql.yml
            service: rbac-mysql
    rbac-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rbac-elasticsearch
